apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scenarios.karness.io
spec:
  group: karness.io
  names:
    kind: Scenario
    plural: scenarios
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status:
          progress:
            type: string
          state:
            type: string
      additionalPrinterColumns:
        - jsonPath: .status.progress
          name: Progress
          type: string
        - jsonPath: .status.state
          name: Status
          type: string
      schema:
        openAPIV3Schema:
          type: object
          description: ""
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            status:
              type: object
              properties:
                progress:
                  description:
                  type: string
                state:
                  type: string
            spec:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                events:
                  type: array
                  items:
                    type: object
                    description: ""
                    properties:
                      name:
                        description: "name of event"
                        type: string
                      description:
                        description: "description of event"
                        type: string
                      action:
                        description: "action invoked by current event"
                        type: object
                        properties:
                          name:
                            type: string
                          body:
                            type: object
                            properties:
                              kv:
                                x-kubernetes-preserve-unknown-fields: true
                                description: "represent JSON"
                                type: object
                              byte:
                                type: string
                                description: "contains base64 bytes value"
                              string:
                                type: string
                          grpc:
                            type: object
                            required: ["addr", "package","service","rpc"]
                            properties:
                              addr:
                                type: string
                              package:
                                type: string
                              service:
                                type: string
                              rpc:
                                type: string
                          http:
                            type: object
                            properties:
                              addr:
                                type: string
                              method:
                                type: string
                      complete:
                        type: object
                        properties:
                          name:
                            type: string
                          condition:
                            type: array
                            items:
                              type: object
                              description: Condition of complete show reason
                              properties:
                                response:
                                  description: ConditionSource contains competition condition for source
                                  type: object
                                  properties:
                                    status:
                                      type: string
                                    body:
                                      type: object
                                      properties:
                                        kv:
                                          x-kubernetes-preserve-unknown-fields: true
                                          description: "represent JSON"
                                          type: object
                                        byte:
                                          type: string
                                          description: "contains base64 bytes value"
                                        string:
                                          type: string




